apiVersion: v1
kind: Pod
metadata:
  name: numbers-captcha
  labels:
    app: my-app
    environment: production
spec:
  containers:
    - name: fastapi
      image: registry.aisingapore.net/aiap-14-dsp/numbers_captcha_fastapi
      command: ["/bin/sh", "-c"]
      args: ["while true; do echo 'FastAPI is running' >> /date.log; sleep 1; done"]
      volumeMounts:
      - name: sample-project-pvc
        mountPath: /pvc
      workingDir: /sample-project-pvc/workspaces/tyn-long-hdb

    - name: streamlit
      image: registry.aisingapore.net/aiap-14-dsp/numbers_captcha_streamlit
      command: ["/bin/sh", "-c"]
      args: ["while true; do echo 'Streamlit is running' >> /date.log; sleep 1; done"]
      volumeMounts:
      - name: sample-project-pvc
        mountPath: /pvc
      workingDir: /sample-project-pvc/workspaces/tyn-long-hdb

  volumes:
  - name: sample-project-pvc
    persistentVolumeClaim:
      claimName: sample-project-pvc
