apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: registry.aisingapore.net/aiap-14-dsp/numbers_captcha_streamlit_app:shun_ping_ong
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: http://172.19.152.111:30594

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit 
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort
